### ISSUE TITLE
brew install throws error

### ISSUE THREAD

**Issue by tthil** [cuber/homebrew-secp256k1#1]
After brew tap cuber/homebrew-libsecp256k1 the brew install libsecp256k1 throws an error.

`Error: An exception occurred within a child process:
  MethodDeprecatedError: Calling BuildOptions#universal? is disabled! There is no replacement.
Please report this issue to the cuber/libsecp256k1 tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/cuber/homebrew-libsecp256k1/libsecp256k1.rb:15`

//Thomas

**Comment by brandisimus** [comment]
The same issue for me, executing `brew install --debug libsecp256k1` produces (extract):

```
.
.
.
cp -pR /private/tmp/d20201230-77125-1ef41iq/sage/. /private/tmp/libsecp256k1-20201230-77125-3hk7ql/sage
cp -pR /private/tmp/d20201230-77125-1ef41iq/autogen.sh /private/tmp/libsecp256k1-20201230-77125-3hk7ql/autogen.sh
cp -pR /private/tmp/d20201230-77125-1ef41iq/src/. /private/tmp/libsecp256k1-20201230-77125-3hk7ql/src
git --git-dir /Users/aaa/Library/Caches/Homebrew/libsecp256k1--git/.git show -s --format=\%cD
/usr/local/Homebrew/Library/Taps/cuber/homebrew-libsecp256k1/libsecp256k1.rb:15:in 'install'
NoMethodError: undefined method 'universal?' for #<BuildOptions:0x00007fdf731a39e8>
1. raise
2. backtrace
3. shell
Choose an action: Multiple options match: raise backtrace shell
.
.
.

Error: An exception occurred within a child process:
  RuntimeError: Aborted due to non-zero exit status (127)
/usr/local/Homebrew/Library/Homebrew/debrew.rb:18:in `raise'
/usr/local/Homebrew/Library/Homebrew/utils.rb:286:in `interactive_shell'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:147:in `block (3 levels) in debug'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:85:in `choose'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:124:in `block in debug'
.
.
.
```
on MacOS Big Sur v.11.1
